<?php

require_once "modules/Module.php";

class Play extends Module
{
    public function getContent()
    {
        if ($_POST['back'] ?? null) {
            header('Location: index.php?module=Home');
            return;
        }
        if ($_POST['newgame'] ?? null) {
            $sql = $this->db->prepare('INSERT INTO games (player1, react_state) VALUES (:player1, :react_state)');
            $sql->execute([':player1' => $_SESSION['user'], ':react_state' => $this->getReactState()]);
            $id = $this->db->lastInsertId();
            header("Location: index.php?module=Game&id=$id");
            return;
        }

        $this->smarty->assign('user', $_SESSION['user']);
    }

    private function getReactState()
    {
        $react_state = [
            "currentAction" => "",
            "wheelbuttons" => [
                "wheel-A1" => [
                    "selectable" => false,
                    "selected" => false,
                    "action" => "forest",
                ],
                "wheel-A2" => [
                    "selectable" => false,
                    "selected" => false,
                    "action" => "lake",
                ],
                "wheel-B1" => [
                    "selectable" => false,
                    "selected" => false,
                    "action" => "mountain",
                ],
                "wheel-B2" => [
                    "selectable" => false,
                    "selected" => false,
                    "action" => "prairie",
                ],
                "wheel-B3" => [
                    "selectable" => false,
                    "selected" => false,
                    "action" => "draw",
                ],
                "wheel-C1" => [
                    "selectable" => false,
                    "selected" => false,
                    "action" => "desert",
                ],
                "wheel-C2" => [
                    "selectable" => false,
                    "selected" => false,
                    "action" => "faeria",
                ],
            ],
            "hand" => [
                1 => [
                    "selectable" => false,
                    "selected" => false,
                ],
                2 => [
                    "selectable" => false,
                    "selected" => false,
                ],
                3 => [
                    "selectable" => false,
                    "selected" => false,
                ],
                4 => [
                    "selectable" => true,
                    "selected" => false,
                ],
                5 => [
                    "selectable" => false,
                    "selected" => false,
                ],
                6 => [
                    "selectable" => false,
                    "selected" => false,
                ],
                7 => [
                    "selectable" => false,
                    "selected" => false,
                ],
                8 => [
                    "selectable" => false,
                    "selected" => false,
                ],
                9 => [
                    "selectable" => false,
                    "selected" => false,
                ],
            ],
            "tiles" => [
                "A1" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["A2", "B2", "B3"],
                    "adjacentNonTile" => "A0",
                ],
                "A2" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["A1", "B3", "B4"],
                    "adjacentNonTile" => "A3",
                ],
                "B1" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["B2", "C1", "C2"],
                    "adjacentNonTile" => "A0",
                ],
                "B2" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["A1", "B1", "B3", "C2", "C3"],
                    "adjacentNonTile" => "A0",
                ],
                "B3" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["A1", "A2", "B2", "B4", "C3", "C4"],
                    "adjacentNonTile" => null,
                ],
                "B4" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["A2", "B3", "B5", "C4", "C5"],
                    "adjacentNonTile" => "A3",
                ],
                "B5" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["B4", "C5", "C6"],
                    "adjacentNonTile" => "A3",
                ],
                "C1" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["B1", "C2", "D1"],
                    "adjacentNonTile" => "D0",
                ],
                "C2" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["B1", "B2", "C1", "C3", "D1", "D2"],
                    "adjacentNonTile" => null,
                ],
                "C3" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["B2", "B3", "C2", "C4", "D2", "D3"],
                    "adjacentNonTile" => null,
                ],
                "C4" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["B3", "B4", "C3", "C5", "D3", "D4"],
                    "adjacentNonTile" => null,
                ],
                "C5" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["B4", "B5", "C4", "C6", "D4", "D5"],
                    "adjacentNonTile" => null,
                ],
                "C6" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["B5", "C5", "D5"],
                    "adjacentNonTile" => "D6",
                ],
                "D1" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["C1", "C2", "D2", "E1", "E2"],
                    "adjacentNonTile" => "D0",
                ],
                "D2" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["C2", "C3", "D1", "D3", "E2", "E3"],
                    "adjacentNonTile" => null,
                ],
                "D3" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["C3", "C4", "D2", "D4", "E3", "E4"],
                    "adjacentNonTile" => null,
                ],
                "D4" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["C4", "C5", "D3", "D5", "E4", "E5"],
                    "adjacentNonTile" => null,
                ],
                "D5" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["C5", "C6", "D4", "E5", "E6"],
                    "adjacentNonTile" => null,
                ],
                "E1" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["D1", "E2", "F1"],
                    "adjacentNonTile" => "D0",
                ],
                "E2" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["D1", "D2", "E1", "E3", "F1", "F2"],
                    "adjacentNonTile" => null,
                ],
                "E3" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["D2", "D3", "E2", "E4", "F2", "F3"],
                    "adjacentNonTile" => null,
                ],
                "E4" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["D3", "D4", "E3", "E5", "F3", "F4"],
                    "adjacentNonTile" => null,
                ],
                "E5" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["D4", "D5", "E4", "E6", "F4", "F5"],
                    "adjacentNonTile" => null,
                ],
                "E6" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["D5", "E5", "F5"],
                    "adjacentNonTile" => "D6",
                ],
                "F1" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["E1", "E2", "F2"],
                    "adjacentNonTile" => "G0",
                ],
                "F2" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["E2", "E3", "F1", "F3", "G1"],
                    "adjacentNonTile" => "G0",
                ],
                "F3" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["E3", "E4", "F2", "F4", "G1", "G2"],
                    "adjacentNonTile" => null,
                ],
                "F4" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["E4", "E5", "F3", "F5", "G2"],
                    "adjacentNonTile" => "G3",
                ],
                "F5" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["E5", "E6", "F4"],
                    "adjacentNonTile" => "G3",
                ],
                "G1" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["F2", "F3", "G2"],
                    "adjacentNonTile" => "G0",
                ],
                "G2" => [
                    "selectable" => false,
                    "selected" => false,
                    "occupantSelectable" => false,
                    "occupantSelected" => false,
                    "adjacent" => ["F3", "F4", "G1"],
                    "adjacentNonTile" => "G3",
                ],
            ],
            "gods" => [
                "D0" => [
                    "selectable" => false,
                    "player" => "player2",
                    "adjacent" => ["C1", "D1", "E1"],
                ],
                "D6" => [
                    "selectable" => false,
                    "player" => "player1",
                    "adjacent" => ["C6", "D5", "E6"],
                ],
            ],
            "data" => [
                "status" => [
                    "finished" => false,
                    "winner" => "",
                    "turn" => 0,
                    "current" => "player1",
                ],
                "board" => [
                    "wells" => [
                        "A0" => [
                            "available" => true,
                            "collected" => false,
                            "adjacent" => ["A1", "B1", "B2"],
                        ],
                        "A3" => [
                            "available" => true,
                            "collected" => false,
                            "adjacent" => ["A2", "B4", "B5"],
                        ],
                        "G0" => [
                            "available" => true,
                            "collected" => false,
                            "adjacent" => ["G1", "F1", "F2"],
                        ],
                        "G3" => [
                            "available" => true,
                            "collected" => false,
                            "adjacent" => ["G2", "F4", "F5"],
                        ],
                    ],
                    "tiles" => [
                        "A1" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "A2" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "B1" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "B2" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "B3" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "B4" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "B5" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "C1" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "C2" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "C3" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "C4" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "C5" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "C6" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "D1" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "D2" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "D3" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "D4" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "D5" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "E1" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "E2" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "E3" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "E4" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "E5" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "E6" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "F1" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "F2" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "F3" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "F4" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "F5" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "G1" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                        "G2" => [
                            "type" => "none",
                            "owner" => "",
                            "occupant" => [
                                "player" => "",
                                "id" => 0,
                                "type" => "",
                                "faeria_cost" => 0,
                                "land_cost" => [
                                    "forest" => 0,
                                    "desert" => 0,
                                    "mountain" => 0,
                                    "lake" => 0,
                                    "wild" => 0,
                                ],
                                "attack" => 0,
                                "base_attack" => 0,
                                "health" => 0,
                                "base_health" => 0,
                                "movement" => [
                                    "range" => 1,
                                    "haste" => true,
                                    "dash" => 0,
                                    "special" => [
                                        "aquatic" => false,
                                        "flying" => false,
                                        "jump" => false,
                                    ],
                                ],
                                "taunt" => false,
                                "divine" => false,
                                "protection" => false,
                                "ranged" => false,
                                "hasMoved" => false,
                                "hasDashed" => false,
                                "hasAttacked" => false,
                                "effects" => [ 
                                    "summon" => false, 
                                    "gift" => false, 
                                    "lastword" => false,
                                    "production" => false,
                                ],
                                "effectUsed" => false,
                            ],
                        ],
                    ],
                    "gods" => [
                        "D0" => [
                            "health" => 20,
                            "wasHit" => false,
                        ],
                        "D6" => [
                            "health" => 20,
                            "wasHit" => false,
                        ],
                    ],
                ],
                "player1" => [
                    "name" => $this->getUserName(),
                    "shuffle" => false,
                    "mulligan" => true,
                    "wheel_used" => true,
                    "wheel_neutral_counter" => 0,
                    "health_dmg" => 0,
                    "faeria" => 3,
                    "hand" => [],
                    "deck" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],
                    "cards" => $this->getCards(),
                ],
                "player2" => [
                    "name" => "player2",
                    "shuffle" => false,
                    "mulligan" => true,
                    "wheel_used" => true,
                    "wheel_neutral_counter" => 0,
                    "health_dmg" => 0,
                    "faeria" => 3,
                    "hand" => [],
                    "deck" => [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],
                    "cards" => [],
                ],
            ],
        ];
        return json_encode($react_state);
    }

    private function getUserName()
    {
        $sql = $this->db->prepare('SELECT * FROM users WHERE id = :id');
        $sql->execute([':id' => $_SESSION['user']]);
        $user = $sql->fetch(PDO::FETCH_ASSOC);
        return $user['name'];
    }

    private function getCards()
    {
        $deck = $this->getDeck();
        $cards = [];
        $i = 0;
        foreach ($deck as $card) {
            $cards[++$i] = $this->getCard($card);
        }
        return $cards;
    }

    private function getDeck()
    {
        $sql = $this->db->prepare('SELECT * FROM decks WHERE id = :id');
        $sql->execute([':id' => $_SESSION['deck']]);
        $deck = $sql->fetch(PDO::FETCH_ASSOC);
        return json_decode($deck['cards']);
    }

    private function getCard($card_id)
    {
        $sql = $this->db->prepare('SELECT * FROM cards WHERE id = :id');
        $sql->execute([':id' => $card_id]);
        $card = $sql->fetch(PDO::FETCH_ASSOC);
        $result = [
            "id" => (int)$card['id'],
            "type" => $card['type'],
            "faeria_cost" => (int)$card['faeria'],
            "land_cost" => [ 
                "forest" =>  (int)$card['forest'], 
                "desert" =>  (int)$card['desert'], 
                "mountain" =>  (int)$card['mountain'], 
                "lake" =>  (int)$card['lake'], 
                "wild" =>  (int)$card['wild'],
            ],
            "attack" => (int)$card['attack'],
            "base_attack" => (int)$card['attack'],
            "health" => (int)$card['health'],
            "base_health" => (int)$card['health'],
            "movement" => [
                "range" => (int)$card['movement_range'],
                "haste" => boolval($card['haste']),
                "dash" => (int)$card['dash'],
                "special" => [
                    "aquatic" => boolval($card['aquatic']),
                    "flying" => boolval($card['flying']),
                    "jump" => boolval($card['jump']),
                ],
            ],
            "taunt" => boolval($card['taunt']),
            "divine" => boolval($card['divine']),
            "protection" => boolval($card['protection']),
            "ranged" => boolval($card['ranged']),
            "effects" => [
                "summon" => boolval($card['summon']), 
                "gift" => boolval($card['gift']),
                "lastword" => boolval($card['lastword']), 
                "production" => boolval($card['production']),
                "target" => boolval($card['target']),
            ],
            "legendary" => boolval($card['legendary']),
        ];
        return $result;
    }
}